let code1;
code1 = 7 + 3;
let code2 = 50 - 20 / 2;
let code3 = (28 % 5) + 36;
let message = "The vault has been secured. The combination is:";
let codeA = code1 + "-" + code2 + "-" + code3;
const codeB = `${code1}-${code2}-${code3}`;
console.log(message);
console.log(codeA);
console.log(codeB);
